### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by Divshub13** [msgithubcodebase/sample-script-1#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by kishore7403** [comment]
Hello!!

**Comment by ChrisHornPersonal** [comment]
This is a massive issue, I'm really concerned about it.

**Comment by RobertCalgary** [comment]
Add a comment

**Comment by byutest1** [comment]
Thank you.

**Comment by bsmithcalgary** [comment]
Hi

**Comment by RogerGihtub** [comment]
Hello!  Thanks for the course.

**Comment by jaehwanahn** [comment]
Demanding to make me a collaborator

**Comment by alin-balan** [comment]
Piling up another comment

**Comment by shreyaa12** [comment]
In this!

**Comment by williamkao1928** [comment]
comment

**Comment by williamkao1928** [comment]
> Demanding to make me a collaborator

so needy

**Comment by marialaura-diazpena** [comment]
I am here!!! sorry

**Comment by tlokken** [comment]
hello!

**Comment by sgokaniCalgary** [comment]
Hi

**Comment by nicoleescoto** [comment]
Hi there!
